# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Python MQTT Soundboard
version: "1.1.5"
slug: python-mqtt-dashboard
description: Python MQTT Soundboard
url: "https://github.com/martinrioux/hassos_python_mqtt_soundboard"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
audio: true
host_network: true
map:
  - media
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
