# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Python MQTT Soundboard
version: "1.0.0"
slug: python-mqtt-dashboard
description: Python MQTT Soundboard
url: "https://github.com/martinrioux/hassos_python_mqtt_soundboard"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - media:rw
options:
  username: "mqtt_user"
  password: "mqtt_user"
schema:
  username: str
  password: str
